[package]
name = "phf_codegen"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.12.0"
license = "MIT"
description = "Codegen library for PHF types"
repository = "https://github.com/rust-phf/rust-phf"
edition = "2021"
readme = "../README.md"
rust-version = "1.60"
categories = ["data-structures"]

[dependencies]
phf_generator = { version = "^0.12.0", path = "../phf_generator"}
phf_shared = { version = "^0.12.0", features = ["uncased", "unicase"], path = "../phf_shared"}
